export const builtIns = {
  PI: Math.PI,
  sin: Math.sin,
  abs: Math.abs,
  acos: Math.acos,
  asin: Math.asin,
  atan: Math.atan,
  atan2: Math.atan2,
  cbrt: Math.cbrt,
  ceil: Math.ceil,
  cos: Math.cos,
  exp: Math.exp,
  floor: Math.floor,
  max: Math.max,
  min: Math.min,
  pow: Math.pow,
  random: Math.random,
  sign: Math.sign,
  sqrt: Math.sqrt,
  tan: Math.tan,
  trunc: Math.trunc
}